cassandra:
  public_ip: localhost
  username: cassandra
  password: cassandra
  keyspace: masterdata

log:
  level: info
  output: logs/app_log-%Y-%m-%d.log
  map:
    time: "@timestamp"
    msg: message